import { Roboto } from 'next/font/google'
import './globals.css'
import Header from '@/components/layout/Header'
import { AppProvider } from '@/components/AppContext'
import { Toaster } from 'react-hot-toast'

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] })

export const metadata = {
  title: 'QuickEats',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={roboto.className}>
        <main className='max-w-4xl mx-auto p-4'>
          <AppProvider>
             <Toaster />       {/* For alerts and pop-up messages */}
            <Header />
            {children}
            <footer className="border-t p-8 text-center text-gray-500 mt-16 bg-red-400 rounded-3xl">
              &copy; 2024 All rights reserved
              <div className="grid grid-cols-3 gap-4">
                <div className="col-span-1 text-center text-gray-500">Grid 1 Content</div>
                <div className="col-span-1 text-center text-gray-500">Grid 2 Content</div>
                <div className="col-span-1 text-center text-gray-500">Grid 3 Content</div>
              </div>
            </footer>
          </AppProvider>
        </main>
      </body>
    </html>
  )
}
